### ISSUE TITLE
C30 - World Topo Map (inkl. Hillshades) works Preplanned, but not AddHoc Offline

### ISSUE THREAD

**Issue by trichtl** [doug-m/CollectorAuroraTesting#210]
Dear Esri-Team,

Software: Collector 
Version : Build 2469
OS      : iOS 12.1 - iPad Air 2

Description:

WebMap with a simple Featureservice and Worldtopo and Hillshade service - we define a Preplanned Area, there the packaging works well and could be taken sucessfully offline.

When we start an Add-Hoc Download it always stopps immediatly - error shows that tile services doesn't support to take offline:

06.11.18, 15:31 Found an Exploded Map Package at: file:///private/var/mobile/Containers/Data/Application/471FBCF0-DB56-4668-80FF-4CDF523CC05D/Documents/trichtl@Ok7pjj1jT9rEneC7/a1f85e7b9fb24536a6ff0e1ae7e0c67e/696C1B0C-9F65-45FD-A01D-58F9CA0D437F/ 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 3/6: Loading online map. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 6/6: Job failed. Job error 7007 Tile export not enabled. Map service does not support export tiles https://services.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 5/6: Fetching feature service infos. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Error downloading map: Error Domain=com.esri.arcgis.runtime.error Code=7007 "Tile export not enabled" UserInfo={NSLocalizedFailureReason=Map service does not support export tiles https://services.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer, NSLocalizedDescription=Tile export not enabled, Additional Message=Map service does not support export tiles https://services.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer} 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Progress: 0.08 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 2/6: Loading offline map task. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - job failed 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 4/6: Loading online layers. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 1/6: Job started. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 3/5: Loading online map. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Progress: 0.06 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - job started 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 4/5: Loading online layers. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 2/5: Loading offline map task. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 5/5: Fetching feature service infos. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 1/5: Job started. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 4/4: Loading online layers. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 2/4: Loading offline map task. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 3/4: Loading online map. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - job started 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 1/4: Job started. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Progress: 0.04 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 3/3: Loading online map. 
06.11.18, 15:31 Found an Exploded Map Package at: file:///private/var/mobile/Containers/Data/Application/471FBCF0-DB56-4668-80FF-4CDF523CC05D/Documents/trichtl@Ok7pjj1jT9rEneC7/a1f85e7b9fb24536a6ff0e1ae7e0c67e/696C1B0C-9F65-45FD-A01D-58F9CA0D437F/ 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - job started 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - job started 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 2/3: Loading offline map task. 
06.11.18, 15:31 [636B9CBF-17E4-4F94-B31C-1B44D90C3326] - Message 1/3: Job started. 

Full logfile also attached
 

Gerhard "Luigi" Trichtl
[bug.txt](https://github.com/doug-m/CollectorAuroraTesting/files/2555510/bug.txt)
[log.txt](https://github.com/doug-m/CollectorAuroraTesting/files/2555511/log.txt)

**Comment by Kevin-GIS** [comment]
Thank you for the feedback @trichtl 

This sounds like a known issue we're aware of. 

But just to confirm, do you have the option to download the offline map? i.e. do you see 'Add Offline Area'?

Could you please elaborate on this issue further.

**Comment by Kevin-GIS** [comment]
Logged SF 1305

**Comment by trichtl** [comment]
HI @Kevin-GIS - yes preplanned could be correctly downloaded and visualized both Vector tiles and hillshade - yes Add Offline Area is availible in the UI and give me the Option to choose an offline area for download - but on several tries I Hand also during start configure area for download

**Comment by Kevin-GIS** [comment]
This issue has been addressed. Closing this issue.

**Comment by trichtl** [comment]
Hi @Kevin-GIS, just retested with 18.1.0 Build 2535 and it still Fails with iOS 12.1 on a Apple iPad Air2

**Comment by Kevin-GIS** [comment]
@trichtl This has been addressed in our internal build and will be addressed in an upcoming release. Thank you for the feedback.

**Comment by trichtl** [comment]
@Kevin-GIS - Retested with Nov. 20 Holistic Build Version and it Fails on two iOS devices - iOS 13.2.2 (IPhone 10) and also on iPad Air 2 with iOS 12.3.2 - WebMap would be this Item: https://austria.maps.arcgis.com/home/item.html?id=ed1d76432c9e451c9e9e050a7f96fc25 (shared with Public - Name OffEdit
